### ISSUE TITLE
Error when no data in immudb

### ISSUE THREAD

**Issue by KAWAHARA-souta** [AlmaLinux/alma-sbom#44]
If there is no data in immudb, (naturally) an SBOM cannot be generated.

```
libmpeg2-devel:
    version: 0.5.1
    epoch: 0
    release: 24.el9
    arch: i686
    pkgid(sha256?): 38f526b7a282413bc97f9d550ead8c80c4fb1fd3e99f64374fb5fd4a0c448bce
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1721824824.999959 2582136 config.cc:230] gRPC experiments enabled: call_status_override_on_cancellation, event_engine_dns, event_engine_listener, http2_stats_fix, monitoring_experiment, pick_first_new, trace_record_callops, work_serializer_clears_time_cache
Traceback (most recent call last):
  File "/home/khwarizmi/test-sbommaking/alma_sbom.py", line 704, in <module>
    cli_main()
  File "/home/khwarizmi/test-sbommaking/alma_sbom.py", line 678, in cli_main
    sbom = get_info_about_package(
  File "/home/khwarizmi/test-sbommaking/alma_sbom.py", line 377, in get_info_about_package
    immudb_metadata = immudb_info_about_package['Metadata']
KeyError: 'Metadata'
```

When querying the data for this package, the results are as follows:
```
{'timestamp': None}
```

Due to the operational specifications of alma_sbom, only the timestamp is set to None.

**Comment by KAWAHARA-souta** [comment]
This had been fixed #49
