### ISSUE TITLE
KeyError: 'srpm_url'

### ISSUE THREAD

**Issue by KAWAHARA-souta** [AlmaLinux/alma-sbom#47]
I've found an issue that occurs only in epel-release-9-2.el9.noarch.rpm in the range of AlmaLinux 9.2 and later packages.

```
$ python alma_sbom.py --rpm-package epel-release-9-2.el9.noarch.rpm --file-format spdx-json --output-file dust
Sep 06 10:53:36 alma-sbom: [WARNING] build info are lacking.
Traceback (most recent call last):
  File "/home/khwarizmi/alma-sbom/alma_sbom.py", line 797, in <module>
    cli_main()
  File "/home/khwarizmi/alma-sbom/alma_sbom.py", line 767, in cli_main
    sbom = get_info_about_package(
  File "/home/khwarizmi/alma-sbom/alma_sbom.py", line 467, in get_info_about_package
    result['metadata']['component'] = _get_each_package_component(
  File "/home/khwarizmi/alma-sbom/alma_sbom.py", line 366, in _get_each_package_component
    _add_package_source_info(
  File "/home/khwarizmi/alma-sbom/alma_sbom.py", line 260, in _add_package_source_info
    'value': immudb_metadata['srpm_url'],
KeyError: 'srpm_url'
```

**Comment by KAWAHARA-souta** [comment]
Note:
This issue occured in the #26 fixed version.

**Comment by KAWAHARA-souta** [comment]
This had been fixed #49
